/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author io
 */
public class IUPpal extends javax.swing.JFrame {

    int datos;
    double[ ] numeros = new double[10];
     /**
     * Creates new form IUPpal
     */
    public IUPpal() {
        initComponents();
        datos = 0;
        activarDesactivarBotonCalcular();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_Num = new javax.swing.JTextField();
        Btn_Agregar = new javax.swing.JButton();
        Btn_Calcular = new javax.swing.JButton();
        Btn_Reniciar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Lbl_Numeros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Txt_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NumActionPerformed(evt);
            }
        });
        Txt_Num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_NumKeyTyped(evt);
            }
        });

        Btn_Agregar.setText("Agregar");
        Btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarActionPerformed(evt);
            }
        });

        Btn_Calcular.setText("Calcular");
        Btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CalcularActionPerformed(evt);
            }
        });

        Btn_Reniciar.setText("Reiniciar");
        Btn_Reniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lbl_Numeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Reniciar)
                                .addGap(28, 28, 28)
                                .addComponent(Btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Txt_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Agregar)))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Agregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_Numeros, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Reniciar)
                    .addComponent(Btn_Calcular))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarActionPerformed
        if(Txt_Num.getText().trim().isEmpty()){
            Utilidades.mostrarMensaje(this, "No ha ingresado un dato válido", "Advertencia", 3);
        }else{
            numeros[datos] = Double.valueOf(Txt_Num.getText().trim());
            datos ++;
            mostrarNumeros();
            activarDesactivarBotonCalcular();
            Txt_Num.setText("");
        }
    }//GEN-LAST:event_Btn_AgregarActionPerformed

    private void Btn_ReniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReniciarActionPerformed
        datos = 0;
        activarDesactivarBotonCalcular();
        mostrarNumeros();
    }//GEN-LAST:event_Btn_ReniciarActionPerformed

    private void Btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CalcularActionPerformed
        Calcular();
    }//GEN-LAST:event_Btn_CalcularActionPerformed

    private void Txt_NumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NumKeyTyped
        Utilidades.validarCampo(evt, 10, 100);
    }//GEN-LAST:event_Txt_NumKeyTyped

    private void Txt_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NumActionPerformed
        Btn_AgregarActionPerformed(evt);
    }//GEN-LAST:event_Txt_NumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Agregar;
    private javax.swing.JButton Btn_Calcular;
    private javax.swing.JButton Btn_Reniciar;
    private javax.swing.JLabel Lbl_Numeros;
    private javax.swing.JTextField Txt_Num;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void activarDesactivarBotonCalcular() {
        if(datos == 10){
            Btn_Calcular.setEnabled(true);
            Btn_Agregar.setEnabled(false);
        }else{
            Btn_Calcular.setEnabled(false);  
            Btn_Agregar.setEnabled(true);          
        }
    }

    private void mostrarNumeros() {
        String r = "";
        for(int i = 0; i<datos; i++){
            r += String.valueOf(numeros[i]) + "<br>";
        }
        Lbl_Numeros.setText("<html><body>"+r+"</body></html>");
    }
    
    private void Calcular() {
        double suma = 0;
        for(int i = 0; i<datos; i++){
            suma += numeros[i];
        }
        Utilidades.mostrarMensaje(this, "El promedio de los números ingresados es: "+String.valueOf(suma/datos), "Promedio", 1);
    }
}
